# Generated by Django 6.1.2 on 2026-10-08 20:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Principal', help_text='Solo para identificarla en el admin.', max_length=100, verbose_name='nombre de la configuración')),
                ('activo', models.BooleanField(default=True, help_text='Solo se usa una configuración activa por ambiente.', verbose_name='activa')),
                ('ambiente', models.PositiveSmallIntegerField(choices=[(1, '1 - Pruebas'), (2, '2 - Producción')], default=1, help_text='1 = pruebas, 2 = producción.', verbose_name='ambiente')),
                ('ruc', models.CharField(max_length=13, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=300, verbose_name='razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, verbose_name='nombre comercial')),
                ('dir_matriz', models.CharField(max_length=300, verbose_name='dirección de la matriz')),
                ('dir_establecimiento', models.CharField(blank=True, help_text='Si se deja vacío se usa la dirección de la matriz.', max_length=300, verbose_name='dirección del establecimiento')),
                ('estab', models.CharField(default='001', max_length=3, verbose_name='establecimiento')),
                ('pto_emi', models.CharField(default='001', max_length=3, verbose_name='punto de emisión')),
                ('obligado_contabilidad', models.BooleanField(default=False, verbose_name='obligado a llevar contabilidad')),
                ('contribuyente_especial', models.CharField(blank=True, help_text='3 a 13 caracteres alfanuméricos. Dejar vacío si no lo es.', max_length=13, verbose_name='n.º de contribuyente especial')),
                ('agente_retencion', models.CharField(blank=True, help_text='Solo dígitos. Dejar vacío si no lo es.', max_length=8, verbose_name='n.º de resolución de agente de retención')),
                ('regimen', models.CharField(blank=True, help_text='Por ejemplo RIMPE. Dejar vacío si es régimen general.', max_length=30, verbose_name='régimen')),
                ('categoria', models.CharField(blank=True, help_text='Por ejemplo NEGOCIO POPULAR (solo si es RIMPE).', max_length=30, verbose_name='categoría')),
                ('certificado', models.FileField(blank=True, help_text='Archivo PKCS#12 con la clave privada y el certificado.', upload_to='sri/certificados/%Y/', validators=[django.core.validators.FileExtensionValidator(['p12', 'pfx'])], verbose_name='archivo de firma (.p12 / .pfx)')),
                ('clave_certificado_cifrada', models.CharField(blank=True, help_text='Se cifra automáticamente; no se muestra en claro.', max_length=500, verbose_name='contraseña del certificado (cifrada)')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'configuración del emisor',
                'verbose_name_plural': 'configuraciones del emisor',
                'ordering': ['-activo', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('ruc', 'estab', 'pto_emi', 'ambiente'), name='sri_fe_emisor_ruc_serie_ambiente')],
            },
        ),
        migrations.CreateModel(
            name='Secuencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Liquidación de compra'), ('04', 'Nota de crédito'), ('05', 'Nota de débito'), ('06', 'Guía de remisión'), ('07', 'Comprobante de retención')], max_length=2)),
                ('estab', models.CharField(max_length=3)),
                ('pto_emi', models.CharField(max_length=3)),
                ('ambiente', models.PositiveSmallIntegerField(default=1)),
                ('ultimo', models.PositiveIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'secuencial',
                'verbose_name_plural': 'secuenciales',
                'constraints': [models.UniqueConstraint(fields=('tipo_comprobante', 'estab', 'pto_emi', 'ambiente'), name='sri_fe_secuencial_unico')],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_acceso', models.CharField(db_index=True, help_text='Clave de 49 dígitos generada con el algoritmo del SRI.', max_length=49, unique=True, verbose_name='clave de acceso')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Liquidación de compra'), ('04', 'Nota de crédito'), ('05', 'Nota de débito'), ('06', 'Guía de remisión'), ('07', 'Comprobante de retención')], default='01', max_length=2, verbose_name='tipo de comprobante')),
                ('ambiente', models.PositiveSmallIntegerField(default=1, help_text='1 = pruebas, 2 = producción.', verbose_name='ambiente')),
                ('tipo_emision', models.CharField(default='1', max_length=1, verbose_name='tipo de emisión')),
                ('estab', models.CharField(default='001', max_length=3, verbose_name='establecimiento')),
                ('pto_emi', models.CharField(default='001', max_length=3, verbose_name='punto de emisión')),
                ('secuencial', models.CharField(max_length=9, verbose_name='secuencial')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('razon_social_receptor', models.CharField(blank=True, max_length=300, verbose_name='razón social del receptor')),
                ('identificacion_receptor', models.CharField(blank=True, max_length=20, verbose_name='identificación del receptor')),
                ('importe_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='importe total')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('RECIBIDO', 'Recibido por el SRI'), ('DEVUELTO', 'Devuelto por el SRI'), ('EN_PROCESO', 'En proceso de autorización'), ('AUTORIZADO', 'Autorizado'), ('NO_AUTORIZADO', 'No autorizado'), ('ERROR', 'Error')], db_index=True, default='BORRADOR', max_length=16, verbose_name='estado')),
                ('numero_autorizacion', models.CharField(blank=True, db_index=True, max_length=49, verbose_name='número de autorización')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de autorización')),
                ('mensajes', models.JSONField(blank=True, default=list, verbose_name='mensajes del SRI')),
                ('intentos', models.PositiveSmallIntegerField(default=0, verbose_name='intentos de envío')),
                ('error', models.TextField(blank=True, verbose_name='último error')),
                ('xml_sin_firma', models.TextField(blank=True, verbose_name='XML sin firmar')),
                ('xml_firmado', models.TextField(blank=True, verbose_name='XML firmado')),
                ('xml_autorizado', models.TextField(blank=True, verbose_name='XML autorizado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='sri_fe.configuracionemisor', verbose_name='configuración del emisor')),
            ],
            options={
                'verbose_name': 'comprobante emitido',
                'verbose_name_plural': 'comprobantes emitidos',
                'ordering': ['-creado'],
                'get_latest_by': 'creado',
                'indexes': [models.Index(fields=['estado', '-creado'], name='sri_fe_estado_creado'), models.Index(fields=['tipo_comprobante', 'secuencial'], name='sri_fe_tipo_secuencial')],
            },
        ),
    ]
