# Generated by Django 6.1.2 on 2026-10-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sri_fe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteemitido',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='tipo de documento'),
        ),
        migrations.AddField(
            model_name='comprobanteemitido',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='id del documento'),
        ),
        migrations.AddIndex(
            model_name='comprobanteemitido',
            index=models.Index(fields=['content_type', 'object_id'], name='sri_fe_documento'),
        ),
    ]
