# Generated by Django 6.1.2 on 2026-10-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_fe', '0003_clientes_productos_y_comprobantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiadestinatario',
            name='cod_doc_sustento',
            field=models.CharField(blank=True, choices=[('01', 'Factura'), ('03', 'Liquidación de compra'), ('04', 'Nota de crédito'), ('05', 'Nota de débito'), ('06', 'Guía de remisión'), ('07', 'Comprobante de retención')], help_text='Solo si los bienes se amparan en otro comprobante: 01 factura, 03 liquidación…', max_length=3, verbose_name='documento que sustenta el traslado'),
        ),
        migrations.AddField(
            model_name='guiadestinatario',
            name='fecha_emision_doc_sustento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha del documento sustento'),
        ),
        migrations.AddField(
            model_name='guiadestinatario',
            name='num_aut_doc_sustento',
            field=models.CharField(blank=True, max_length=49, verbose_name='autorización del documento sustento'),
        ),
        migrations.AddField(
            model_name='guiadestinatario',
            name='num_doc_sustento',
            field=models.CharField(blank=True, help_text='001-001-000000001 (también se acepta 001001000000001).', max_length=17, verbose_name='número del documento sustento'),
        ),
        migrations.AddField(
            model_name='retenciondocsustento',
            name='aplic_conv_dob_trib',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='aplica convenio de doble tributación'),
        ),
        migrations.AddField(
            model_name='retenciondocsustento',
            name='pag_ext_suj_ret_nor_leg',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='pago a sujeto no obligado a llevar contabilidad'),
        ),
        migrations.AddField(
            model_name='retenciondocsustento',
            name='pago_loc_ext',
            field=models.CharField(choices=[('01', 'Local'), ('02', 'Al exterior')], default='01', max_length=2, verbose_name='pago'),
        ),
        migrations.AddField(
            model_name='retenciondocsustento',
            name='pais_efec_pago',
            field=models.CharField(blank=True, help_text='Código del país (3 o 4 dígitos). Solo para pagos al exterior.', max_length=4, verbose_name='país del pago'),
        ),
        migrations.AddField(
            model_name='retenciondocsustento',
            name='tipo_regi',
            field=models.CharField(blank=True, help_text='Solo para pagos al exterior. Tabla del SRI.', max_length=2, verbose_name='tipo de régimen'),
        ),
    ]
