# Generated by Django 6.1.2 on 2026-10-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_fe', '0004_documento_sustento_y_pagos_al_exterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionemisor',
            name='campos_adicionales',
            field=models.TextField(blank=True, help_text='Campos que se añaden a TODOS los comprobantes (hasta 15), en formato NOMBRE=VALOR separados por «;»: VENDEDOR=JOHNNY; SUCURSAL=NORTE. Lo que escriba en cada comprobante tiene prioridad sobre estos valores.', verbose_name='campos adicionales de la tienda'),
        ),
        migrations.AddField(
            model_name='factura',
            name='informacion_adicional',
            field=models.TextField(blank=True, help_text='Opcional, hasta 15 campos propios de la tienda. Formato NOMBRE=VALOR separados por «;»: VENDEDOR=JOHNNY; SUCURSAL=NORTE. Viaja al SRI en «infoAdicional».', verbose_name='campos adicionales'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='datos_adicionales',
            field=models.CharField(blank=True, help_text='Opcional, hasta 3 campos. Formato NOMBRE=VALOR separados por «;»: MARCA=ACME; LOTE=2026-01. Viaja al SRI en «detallesAdicionales».', max_length=1000, verbose_name='datos adicionales'),
        ),
        migrations.AddField(
            model_name='guiadetalle',
            name='codigo_adicional',
            field=models.CharField(blank=True, max_length=25, verbose_name='código adicional'),
        ),
        migrations.AddField(
            model_name='guiadetalle',
            name='datos_adicionales',
            field=models.CharField(blank=True, help_text='Opcional, hasta 3 campos. Formato NOMBRE=VALOR separados por «;»: MARCA=ACME; LOTE=2026-01.', max_length=1000, verbose_name='datos adicionales'),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='informacion_adicional',
            field=models.TextField(blank=True, help_text='Opcional, hasta 15 campos propios de la tienda. Formato NOMBRE=VALOR separados por «;»: VENDEDOR=JOHNNY; SUCURSAL=NORTE. Viaja al SRI en «infoAdicional».', verbose_name='campos adicionales'),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='informacion_adicional',
            field=models.TextField(blank=True, help_text='Opcional, hasta 15 campos propios de la tienda. Formato NOMBRE=VALOR separados por «;»: VENDEDOR=JOHNNY; SUCURSAL=NORTE. Viaja al SRI en «infoAdicional».', verbose_name='campos adicionales'),
        ),
        migrations.AddField(
            model_name='liquidacioncompradetalle',
            name='datos_adicionales',
            field=models.CharField(blank=True, help_text='Opcional, hasta 3 campos. Formato NOMBRE=VALOR separados por «;»: MARCA=ACME; LOTE=2026-01. Viaja al SRI en «detallesAdicionales».', max_length=1000, verbose_name='datos adicionales'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='informacion_adicional',
            field=models.TextField(blank=True, help_text='Opcional, hasta 15 campos propios de la tienda. Formato NOMBRE=VALOR separados por «;»: VENDEDOR=JOHNNY; SUCURSAL=NORTE. Viaja al SRI en «infoAdicional».', verbose_name='campos adicionales'),
        ),
        migrations.AddField(
            model_name='notacreditodetalle',
            name='datos_adicionales',
            field=models.CharField(blank=True, help_text='Opcional, hasta 3 campos. Formato NOMBRE=VALOR separados por «;»: MARCA=ACME; LOTE=2026-01. Viaja al SRI en «detallesAdicionales».', max_length=1000, verbose_name='datos adicionales'),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='informacion_adicional',
            field=models.TextField(blank=True, help_text='Opcional, hasta 15 campos propios de la tienda. Formato NOMBRE=VALOR separados por «;»: VENDEDOR=JOHNNY; SUCURSAL=NORTE. Viaja al SRI en «infoAdicional».', verbose_name='campos adicionales'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='informacion_adicional',
            field=models.TextField(blank=True, help_text='Opcional, hasta 15 campos propios de la tienda. Formato NOMBRE=VALOR separados por «;»: VENDEDOR=JOHNNY; SUCURSAL=NORTE. Viaja al SRI en «infoAdicional».', verbose_name='campos adicionales'),
        ),
    ]
