# Generated by Django 6.1.2 on 2026-10-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_fe', '0005_campos_adicionales_de_la_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteemitido',
            name='carpeta',
            field=models.CharField(blank=True, help_text='Carpeta, dentro de MEDIA_ROOT, con los XML y las respuestas del SRI.', max_length=255, verbose_name='carpeta de archivos'),
        ),
        migrations.AddField(
            model_name='comprobanteemitido',
            name='respuesta_autorizacion',
            field=models.TextField(blank=True, help_text='Respuesta SOAP tal cual llegó, con el comprobante autorizado.', verbose_name='respuesta de autorización del SRI'),
        ),
        migrations.AddField(
            model_name='comprobanteemitido',
            name='respuesta_recepcion',
            field=models.TextField(blank=True, help_text='Respuesta SOAP tal cual llegó (se guarda aunque el comprobante esté mal).', verbose_name='respuesta de recepción del SRI'),
        ),
    ]
