# Generated by Django 6.1.2 on 2026-10-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_fe', '0006_respuestas_y_archivos_del_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='actualizado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='creado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Para enviarle el comprobante. El SRI no lo pide.', max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='actualizado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='creado'),
        ),
    ]
