# Generated by Django 6.1.2 on 2026-10-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_fe', '0007_contacto_y_fechas_en_los_catalogos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionemisor',
            name='ambiente',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pruebas (1) — sin validez fiscal, para ensayar'), (2, 'Producción (2) — con validez legal ante el SRI')], default=1, help_text='Pruebas (1): comprobantes sin validez fiscal, para ensayar. Producción (2): comprobantes con validez legal ante el SRI.', verbose_name='ambiente'),
        ),
    ]
