# Generated by Django 6.1.2 on 2026-10-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_fe', '0008_nombre_de_los_ambientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteemitido',
            name='ambiente',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Pruebas'), (2, '2 - Producción')], default=1, help_text='Ambiente en el que se emitió: pruebas o producción.', verbose_name='ambiente'),
        ),
        migrations.AlterField(
            model_name='configuracionemisor',
            name='ambiente',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Pruebas'), (2, '2 - Producción')], default=1, help_text='Pruebas (1): comprobantes sin validez fiscal, para ensayar. Producción (2): comprobantes con validez legal ante el SRI.', verbose_name='ambiente'),
        ),
        migrations.AlterField(
            model_name='secuencial',
            name='ambiente',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Pruebas'), (2, '2 - Producción')], default=1, verbose_name='ambiente'),
        ),
    ]
