# Generated by Django 6.1.2 on 2026-10-09 02:44

from django.db import migrations, models

#: Unidades que en la práctica se usan para servicios.
UNIDADES_DE_SERVICIO = ("hora", "horas", "servicio", "servicios", "mes", "meses", "visita")


def clasificar_lo_que_ya_existe(apps, schema_editor):
    """Marca como servicio lo que ya estaba guardado con unidad de servicio.

    Los productos anteriores a este cambio quedan como «producto» (el valor por
    omisión). Es una comodidad: se puede cambiar en el admin. La unidad de medida
    vacía se rellena con la que propone el tipo, para que el XML lleve siempre algo.
    """
    Producto = apps.get_model("sri_fe", "Producto")
    for producto in Producto.objects.all():
        cambios = []
        if (producto.unidad_medida or "").strip().lower() in UNIDADES_DE_SERVICIO:
            producto.tipo = "servicio"
            cambios.append("tipo")
        if not (producto.unidad_medida or "").strip():
            producto.unidad_medida = "UNIDAD" if producto.tipo != "servicio" else "SERVICIO"
            cambios.append("unidad_medida")
        if cambios:
            producto.save(update_fields=cambios)


class Migration(migrations.Migration):

    dependencies = [
        ('sri_fe', '0009_nombre_del_ambiente_en_los_comprobantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='datos_adicionales',
            field=models.CharField(blank=True, help_text='Opcional, hasta 3 campos. Formato NOMBRE=VALOR separados por «;»: MARCA=ACME; GARANTIA=12 MESES. Se copian en cada línea del comprobante que use este producto o servicio (y se pueden cambiar en la línea).', max_length=1000, verbose_name='detalles adicionales'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto (bien)'), ('servicio', 'Servicio')], default='producto', help_text='Un bien o un servicio. Sirve para filtrar y buscar en el admin, y para proponer la unidad de medida si la deja vacía.', max_length=10, verbose_name='¿qué es?'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='datos_adicionales',
            field=models.CharField(blank=True, help_text='Opcional, hasta 3 campos. Formato NOMBRE=VALOR separados por «;»: MARCA=ACME; LOTE=2026-01. Viaja al SRI en «detallesAdicionales». Si se elige un producto, se copian los suyos.', max_length=1000, verbose_name='datos adicionales'),
        ),
        migrations.AlterField(
            model_name='liquidacioncompradetalle',
            name='datos_adicionales',
            field=models.CharField(blank=True, help_text='Opcional, hasta 3 campos. Formato NOMBRE=VALOR separados por «;»: MARCA=ACME; LOTE=2026-01. Viaja al SRI en «detallesAdicionales». Si se elige un producto, se copian los suyos.', max_length=1000, verbose_name='datos adicionales'),
        ),
        migrations.AlterField(
            model_name='notacreditodetalle',
            name='datos_adicionales',
            field=models.CharField(blank=True, help_text='Opcional, hasta 3 campos. Formato NOMBRE=VALOR separados por «;»: MARCA=ACME; LOTE=2026-01. Viaja al SRI en «detallesAdicionales». Si se elige un producto, se copian los suyos.', max_length=1000, verbose_name='datos adicionales'),
        ),
        migrations.RunPython(clasificar_lo_que_ya_existe, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Texto libre: unidad, caja, kg, litro, hora… Si la deja vacía se usa UNIDAD para un producto y SERVICIO para un servicio.', max_length=50, verbose_name='unidad de medida'),
        ),
    ]
