# Generated by Django 6.1.2 on 2026-10-09 12:50

import factec.sri.fechas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri_fe', '0010_tipo_y_detalles_adicionales_del_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(default=factec.sri.fechas.hoy_en_ecuador, help_text="Al emitir se ajusta al día de la firma (el reloj del SRI, Ecuador), salvo con FACTURACION_ELECTRONICA['FECHA_EMISION_AL_EMITIR'] = False.", verbose_name='fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='fecha_emision',
            field=models.DateField(default=factec.sri.fechas.hoy_en_ecuador, help_text="Al emitir se ajusta al día de la firma (el reloj del SRI, Ecuador), salvo con FACTURACION_ELECTRONICA['FECHA_EMISION_AL_EMITIR'] = False.", verbose_name='fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='liquidacioncompra',
            name='fecha_emision',
            field=models.DateField(default=factec.sri.fechas.hoy_en_ecuador, help_text="Al emitir se ajusta al día de la firma (el reloj del SRI, Ecuador), salvo con FACTURACION_ELECTRONICA['FECHA_EMISION_AL_EMITIR'] = False.", verbose_name='fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha_emision',
            field=models.DateField(default=factec.sri.fechas.hoy_en_ecuador, help_text="Al emitir se ajusta al día de la firma (el reloj del SRI, Ecuador), salvo con FACTURACION_ELECTRONICA['FECHA_EMISION_AL_EMITIR'] = False.", verbose_name='fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='fecha_emision',
            field=models.DateField(default=factec.sri.fechas.hoy_en_ecuador, help_text="Al emitir se ajusta al día de la firma (el reloj del SRI, Ecuador), salvo con FACTURACION_ELECTRONICA['FECHA_EMISION_AL_EMITIR'] = False.", verbose_name='fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='retencion',
            name='fecha_emision',
            field=models.DateField(default=factec.sri.fechas.hoy_en_ecuador, help_text="Al emitir se ajusta al día de la firma (el reloj del SRI, Ecuador), salvo con FACTURACION_ELECTRONICA['FECHA_EMISION_AL_EMITIR'] = False.", verbose_name='fecha de emisión'),
        ),
    ]
